---
- name: load configuration onto target device
  block:
    - name: enter configuration mode
      cli:
        command: configure terminal

    - name: load configuration lines
      cli:
        command: "{{ line.strip() }}"
      loop: "{{ ios_config_text | to_lines _}}"
      loop_control:
        loop_var: line
      changed_when: true
      when: not ansible_check_mode and line != 'end'

    - name: leave configuration mode
      cli:
        command: end

  rescue:
    - name: leave configuration mode
      cli:
        command: end

    - name: mark the host as failed
      fail:
        msg: "error trying to merge configuration"
